/*=================----  Keys.H ----==================*/

#define HT		     9
#define RUBOUT      8
#define BELL	     7
#define ESC		    27
#define SHIFT_HT  143
#define CTRL_T	    20
#define CTRL_B	     2
#define CTRL_D	     4
#define ALT_D     160

#define F1   187
#define F2   188
#define F3   189
#define F4   190
#define F5   191
#define F6   192
#define F7   193
#define F8   194
#define F9   195
#define F10  196

#define HOME 	199
#define UP		200
#define PGUP	201
#define BS		203
#define FWD		205
#define END		207
#define DN		208
#define PGDN	209
#define INS		210
#define DEL		211

#define CTRL_HOME	 247
#define CTRL_BS	 243
#define CTRL_FWD   244
#define CTRL_END   245
